### ISSUE TITLE
NHOS Flash Tool 1.0.2 is not working under macOS 10.15

### ISSUE THREAD

**Issue by Artem-Kalmykov** [nicehash/NHOS-Flash-Tool#1]
This error message is shown when trying to launch 1.0.2 under macOS 10.15.
<img width="532" alt="Screenshot 2019-12-28 at 12 07 27" src="https://user-images.githubusercontent.com/29488527/71542083-9fa6c380-296a-11ea-8ec1-e770474aa56b.png">

**Comment by usern-spec** [comment]
Fixed in latest release(1.0.2)
