### ISSUE TITLE
Flash tool not downloading latest image.

### ISSUE THREAD

**Issue by ripeart** [nicehash/NHOS-Flash-Tool#11]
OSX 10.15.7

Error downloading image:

![Screen Shot 2021-04-22 at 1 45 50 PM](https://user-images.githubusercontent.com/41564948/115762130-21490e80-a371-11eb-8c32-3b4ecf1f3f54.png)

Getting a lot of device not open errors in console

![Screen Shot 2021-04-22 at 1 47 49 PM](https://user-images.githubusercontent.com/41564948/115762349-5f463280-a371-11eb-8db7-2ebbae3a2a61.png)

**Comment by AeShevch** [comment]
same issue!

**Comment by lyons88** [comment]
Erase the flash drive MSDOS and GUID.

Worked for me to fix this issue.

**Comment by interactiveRob** [comment]
Formatting also solved this issue for me. I am on Mac OS 10.15.6 and had to format the USB drive to ExFat to get it to work

**Comment by qman22** [comment]
I have tried all of this, and the problem persists. 
Plz Help
