### ISSUE TITLE
Can't start FlashTool (1.0.2) on Windows 10.1909

### ISSUE THREAD

**Issue by gromran** [nicehash/NHOS-Flash-Tool#2]
every time, when i try to start the flash tool, it crashes after few seconds (not show any gui)

Event Log:
Name der fehlerhaften Anwendung: nhos-flash-tool.exe, Version: 0.0.0.0, Zeitstempel: 0x5e27385e
Name des fehlerhaften Moduls: nhos-flash-tool.exe, Version: 0.0.0.0, Zeitstempel: 0x5e27385e
Ausnahmecode: 0xc0000005
Fehleroffset: 0x000000000002614d
ID des fehlerhaften Prozesses: 0x3908
Startzeit der fehlerhaften Anwendung: 0x01d5d78d23b9175d
Pfad der fehlerhaften Anwendung: C:\Program Files\nhos-flash-tool 1.0.2\bin\nhos-flash-tool.exe
Pfad des fehlerhaften Moduls: C:\Program Files\nhos-flash-tool 1.0.2\bin\nhos-flash-tool.exe
Berichtskennung: 992af6db-f865-40fe-acdf-fa449af589eb

Fehlerbucket 2154672321245390949, Typ 4
Ereignisname: APPCRASH
Antwort: Nicht verfügbar
CAB-Datei-ID: 0
Problemsignatur:
P1: nhos-flash-tool.exe
P2: 0.0.0.0
P3: 5e27385e
P4: nhos-flash-tool.exe
P5: 0.0.0.0
P6: 5e27385e
P7: c0000005
P8: 000000000002614d
P9: 
P10:

**Comment by usern-spec** [comment]
@gromran Can you reply with NHOS Flash Tool log that can be found at C:\Users\<user>\AppData\Local\NHOS Flash Tool.

Also are you using any anti-virus software that could prevent Flash Tool from running?

**Comment by gromran** [comment]
[NHOS Flash Tool.log](https://github.com/nicehash/NHOS-Flash-Tool/files/4138857/NHOS.Flash.Tool.log)

And the whole install folder is excluded in the defender.

**Comment by usern-spec** [comment]
@gromran Have you tried starting the flash tool without usb flash drive connected to your computer?

**Comment by gromran** [comment]
When i start the tool with no stick attached, the tool comes up. Then in the moment when i attached the stick the tool close without any notice (but with the error from above)

edit: I have now created the stick with Rufus. That worked. (So whether the stick will boot on the rig, I don't know yet ^^). Still, it would be better if the tool worked as intended.

**Comment by usern-spec** [comment]
@gromran Any way you could try a private build of NHOS Flash Tool to check if the issue is resolved?
As the problem seems to be in windows usb enumeration, and i could not repeat the crash on my device.

**Comment by gromran** [comment]
Yes I can.
But, I tested the "old" tool on another computer. Same problem. I think maybe the stick is the problem. Will test it too.

edit: I found my other stick and tested it: it works. So it's stick related. (The other works normally when reading/writing data, he only has problems with the tool)
