### ISSUE TITLE
NHOS Flash Tool fails to launch on Ubuntu 20.04

### ISSUE THREAD

**Issue by damonlynch** [nicehash/NHOS-Flash-Tool#3]
This is the output from journalctl

```
May 15 09:22:26 X570 systemd[1799]: Started Application launched by gnome-shell.
May 15 09:22:28 X570 polkitd(authority=local)[1561]: Operator of unix-session:1 successfully authenticated as unix-user:damon to gain ONE-SHOT authorization for action org.freedesktop.policykit.exec for unix-process:15542:68088 [sh -c pkexec env DISPLAY=:0 XAUTHORITY=/run/>
May 15 09:22:28 X570 pkexec[15543]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)
May 15 09:22:28 X570 pkexec[15543]: damon: Executing command [USER=root] [TTY=unknown] [CWD=/home/damon] [COMMAND=/usr/bin/env DISPLAY=:0 XAUTHORITY=/run/user/1000/gdm/Xauthority sudo /usr/local/nhos-flash-tool /home/damon/.local/share/NHOS Flash Tool]
May 15 09:22:28 X570 sudo[15543]:     root : TTY=unknown ; PWD=/root ; USER=root ; COMMAND=/usr/local/nhos-flash-tool /home/damon/.local/share/NHOS Flash Tool
May 15 09:22:28 X570 sudo[15543]: pam_unix(sudo:session): session opened for user root by (uid=0)
May 15 09:22:28 X570 NHOS Flash Tool.desktop[15549]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
May 15 09:22:28 X570 NHOS Flash Tool.desktop[15549]: corrupted size vs. prev_size
May 15 09:22:28 X570 sudo[15543]: pam_unix(sudo:session): session closed for user root
May 15 09:22:28 X570 NHOS Flash Tool.desktop[15542]: Aborted
May 15 09:22:28 X570 NHOS Flash Tool.desktop[15538]: sh -c "pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY sudo '/usr/local/nhos-flash-tool' '/home/damon/.local/share/NHOS Flash Tool'"
May 15 09:22:28 X570 systemd[1799]: gnome-launched-NHOS_Flash_Tool.desktop-15538.scope: Succeeded.
lines 
```

**Comment by lpspot** [comment]
Same here (20.04). Could run it once (1.0.6) but after a while was gone.
Issue persists after dpkg purge and new install.
 
/usr/local/nhos-flash-tool 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
corrupted size vs. prev_size
Aborted

**Update**: It seems to be related with the usb stick, when unplugged I can launch the tool but it crashes as soon as I plug it back:
**~$ sudo /usr/local/nhos-flash-tool** 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QObject::connect: No such signal image_retriever::image_downloaded()
--USB stick plugged--
corrupted size vs. prev_size
Aborted

**syslog:**
Feb 26 22:41:01 nucambo kernel: [ 2817.852918] usb 2-3: new SuperSpeed Gen 1 USB device number 11 using xhci_hcd
Feb 26 22:41:01 nucambo kernel: [ 2817.873463] usb 2-3: New USB device found, idVendor=0781, idProduct=5580, bcdDevice= 0.10
Feb 26 22:41:01 nucambo kernel: [ 2817.873466] usb 2-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Feb 26 22:41:01 nucambo kernel: [ 2817.873468] usb 2-3: Product: Extreme
Feb 26 22:41:01 nucambo kernel: [ 2817.873469] usb 2-3: Manufacturer: SanDisk
Feb 26 22:41:01 nucambo kernel: [ 2817.873470] usb 2-3: SerialNumber: AA011027151304500631
Feb 26 22:41:01 nucambo kernel: [ 2817.874881] usb-storage 2-3:1.0: USB Mass Storage device detected
Feb 26 22:41:01 nucambo kernel: [ 2817.875021] scsi host3: usb-storage 2-3:1.0
Feb 26 22:41:01 nucambo mtp-probe: checking bus 2, device 11: "/sys/devices/pci0000:00/0000:00:14.0/usb2/2-3"
Feb 26 22:41:01 nucambo mtp-probe: bus: 2, device: 11 was not an MTP device
Feb 26 22:41:01 nucambo mtp-probe: checking bus 2, device 11: "/sys/devices/pci0000:00/0000:00:14.0/usb2/2-3"
Feb 26 22:41:01 nucambo mtp-probe: bus: 2, device: 11 was not an MTP device
Feb 26 22:41:02 nucambo kernel: [ 2818.881188] scsi 3:0:0:0: Direct-Access     SanDisk  Extreme          0001 PQ: 0 ANSI: 6
Feb 26 22:41:02 nucambo kernel: [ 2818.881468] sd 3:0:0:0: Attached scsi generic sg1 type 0
Feb 26 22:41:02 nucambo kernel: [ 2818.881635] sd 3:0:0:0: [sdb] 61282631 512-byte logical blocks: (31.4 GB/29.2 GiB)
Feb 26 22:41:02 nucambo kernel: [ 2818.881827] sd 3:0:0:0: [sdb] Write Protect is off
Feb 26 22:41:02 nucambo kernel: [ 2818.881830] sd 3:0:0:0: [sdb] Mode Sense: 53 00 00 08
Feb 26 22:41:02 nucambo kernel: [ 2818.882025] sd 3:0:0:0: [sdb] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
Feb 26 22:41:02 nucambo kernel: [ 2818.979130]  sdb:
Feb 26 22:41:02 nucambo kernel: [ 2818.980322] sd 3:0:0:0: [sdb] Attached SCSI removable disk

**Comment by reynoldsme** [comment]
Same on Kubuntu 20.04 on two very different machines. I tried with three different Flash drives and the crash only happens once a flash drive is inserted.
The exact message seems to vary, but these are the three messages I've gotten just before `Aborted` 

`corrupted size vs. prev_size`

`nhos-flash-tool: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.`

`malloc(): mismatching next->prev_size (unsorted)`

**Comment by brianivander** [comment]
Any update how to solve this? I'm having the same problem on Ubuntu 20.04. The USB flash app opens, but then closes after I insert the USB Flash disk.

**Comment by alesaudate** [comment]
Same here

**Comment by grantschneider** [comment]
hi, any update here?

**Comment by isnuryusuf** [comment]
Any update?

**Comment by rabinnh** [comment]
Fully up to date Ubuntu 20.04

xxxx@rxxxxx:~$ /usr/local/nhos-flash-tool
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
corrupted size vs. prev_size
Aborted
sh -c "pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY sudo '/usr/local/nhos-flash-tool' '/home/xxxxx/.local/share/NHOS Flash Tool'"

**Comment by jkbmaj** [comment]
Same problem @ Ubuntu 20.04 after NHOS update to latest version:
```/usr/local/nhos-flash-tool 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
nhos-flash-tool: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted
sh -c "pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY sudo '/usr/local/nhos-flash-tool' '/home/jakub/.local/share/NHOS Flash Tool'"%```

**Comment by clay53** [comment]
Doing a sketchy way to get this running on Arch, also has this problem.

**Comment by CyKrome007** [comment]
Same here. I tried with many different usb sticks also tried formatting each one of the but no good 
: (

**Comment by VGerris** [comment]
same here, completely broken. happens on USB plugin. 
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QObject::connect: No such signal image_retriever::image_downloaded()
Unknown property font-stretch
Unknown property font-stretch
corrupted size vs. prev_size
Aborted

```

as root, otherwise as the above,
workaround is to flash the image:
https://github.com/nicehash/NHOS/blob/master/nhos_create_flash_drive.md

But then all settings need to be manually changed. 
this sucks.
Please fix this @Nicehash

**Comment by kdvolder** [comment]
Not launching on ubuntu 18.04 either.

**Comment by MrJimmyPenguin** [comment]
This is still an issue with ubuntu distros based on 20.04, including popos.
