### ISSUE TITLE
wifi

### ISSUE THREAD

**Issue by seisdr** [nicehash/NHOS-Flash-Tool#5]
I can write my wifi name which is just "k"
the wifi ssid is "k"
and the program crash after finishing the burning

**Comment by usern-spec** [comment]
@seisdr Fixed in the newest release (1.0.6).

**Comment by seisdr** [comment]
![IMG_20201217_233230](https://user-images.githubusercontent.com/45742462/102540511-31e63100-40c0-11eb-9983-3c82a4d0582e.jpg)
no
