### ISSUE TITLE
ISO image

### ISSUE THREAD

**Issue by DaemoncheG** [nicehash/NHOS-Flash-Tool#6]
Where to download an iso image for a cd?

**Comment by keithsavage777** [comment]
https://www.nicehash.com/download-center

NiceHash OSMining | Advanced Linux based mining operating system for mining farms. | 1.2.6
-- | -- | --


click download silly

**Comment by DaemoncheG** [comment]
> https://www.nicehash.com/download-center
> 
> NiceHash OSMining	Advanced Linux based mining operating system for mining farms.	1.2.6
> click download silly

*.iso file for record to cd or dvd
