### ISSUE TITLE
wifi name and program crash 

### ISSUE THREAD

**Issue by seisdr** [nicehash/NHOS-Flash-Tool#7]
the latest version didn't fix the issue of the wifi ssid can't write a single character
and it keep crashing 
![IMG_20201219_235016](https://user-images.githubusercontent.com/45742462/102699382-427be000-4255-11eb-8e3b-7cb7ad15c5c5.jpg)
![IMG_20201217_233230](https://user-images.githubusercontent.com/45742462/102699383-46a7fd80-4255-11eb-943e-ffa9bc21f07e.jpg)

**Comment by usern-spec** [comment]
Removed Wireles ssid regex in 1.0.7
